# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /lu1/smagri/uni/subj/proj30cp/catkin_ws/src/voice_node

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /lu1/smagri/uni/subj/proj30cp/catkin_ws/src/voice_node

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /lu1/smagri/uni/subj/proj30cp/catkin_ws/src/voice_node/CMakeFiles /lu1/smagri/uni/subj/proj30cp/catkin_ws/src/voice_node/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /lu1/smagri/uni/subj/proj30cp/catkin_ws/src/voice_node/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _voice_node_generate_messages_check_deps_voice_node

# Build rule for target.
_voice_node_generate_messages_check_deps_voice_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _voice_node_generate_messages_check_deps_voice_node
.PHONY : _voice_node_generate_messages_check_deps_voice_node

# fast build rule for target.
_voice_node_generate_messages_check_deps_voice_node/fast:
	$(MAKE) -f CMakeFiles/_voice_node_generate_messages_check_deps_voice_node.dir/build.make CMakeFiles/_voice_node_generate_messages_check_deps_voice_node.dir/build
.PHONY : _voice_node_generate_messages_check_deps_voice_node/fast

#=============================================================================
# Target rules for targets named clean_test_results

# Build rule for target.
clean_test_results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_test_results
.PHONY : clean_test_results

# fast build rule for target.
clean_test_results/fast:
	$(MAKE) -f CMakeFiles/clean_test_results.dir/build.make CMakeFiles/clean_test_results.dir/build
.PHONY : clean_test_results/fast

#=============================================================================
# Target rules for targets named download_extra_data

# Build rule for target.
download_extra_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 download_extra_data
.PHONY : download_extra_data

# fast build rule for target.
download_extra_data/fast:
	$(MAKE) -f CMakeFiles/download_extra_data.dir/build.make CMakeFiles/download_extra_data.dir/build
.PHONY : download_extra_data/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named roscpp_generate_messages_cpp

# Build rule for target.
roscpp_generate_messages_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roscpp_generate_messages_cpp
.PHONY : roscpp_generate_messages_cpp

# fast build rule for target.
roscpp_generate_messages_cpp/fast:
	$(MAKE) -f CMakeFiles/roscpp_generate_messages_cpp.dir/build.make CMakeFiles/roscpp_generate_messages_cpp.dir/build
.PHONY : roscpp_generate_messages_cpp/fast

#=============================================================================
# Target rules for targets named roscpp_generate_messages_lisp

# Build rule for target.
roscpp_generate_messages_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roscpp_generate_messages_lisp
.PHONY : roscpp_generate_messages_lisp

# fast build rule for target.
roscpp_generate_messages_lisp/fast:
	$(MAKE) -f CMakeFiles/roscpp_generate_messages_lisp.dir/build.make CMakeFiles/roscpp_generate_messages_lisp.dir/build
.PHONY : roscpp_generate_messages_lisp/fast

#=============================================================================
# Target rules for targets named roscpp_generate_messages_py

# Build rule for target.
roscpp_generate_messages_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roscpp_generate_messages_py
.PHONY : roscpp_generate_messages_py

# fast build rule for target.
roscpp_generate_messages_py/fast:
	$(MAKE) -f CMakeFiles/roscpp_generate_messages_py.dir/build.make CMakeFiles/roscpp_generate_messages_py.dir/build
.PHONY : roscpp_generate_messages_py/fast

#=============================================================================
# Target rules for targets named rosgraph_msgs_generate_messages_cpp

# Build rule for target.
rosgraph_msgs_generate_messages_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosgraph_msgs_generate_messages_cpp
.PHONY : rosgraph_msgs_generate_messages_cpp

# fast build rule for target.
rosgraph_msgs_generate_messages_cpp/fast:
	$(MAKE) -f CMakeFiles/rosgraph_msgs_generate_messages_cpp.dir/build.make CMakeFiles/rosgraph_msgs_generate_messages_cpp.dir/build
.PHONY : rosgraph_msgs_generate_messages_cpp/fast

#=============================================================================
# Target rules for targets named rosgraph_msgs_generate_messages_lisp

# Build rule for target.
rosgraph_msgs_generate_messages_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosgraph_msgs_generate_messages_lisp
.PHONY : rosgraph_msgs_generate_messages_lisp

# fast build rule for target.
rosgraph_msgs_generate_messages_lisp/fast:
	$(MAKE) -f CMakeFiles/rosgraph_msgs_generate_messages_lisp.dir/build.make CMakeFiles/rosgraph_msgs_generate_messages_lisp.dir/build
.PHONY : rosgraph_msgs_generate_messages_lisp/fast

#=============================================================================
# Target rules for targets named rosgraph_msgs_generate_messages_py

# Build rule for target.
rosgraph_msgs_generate_messages_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosgraph_msgs_generate_messages_py
.PHONY : rosgraph_msgs_generate_messages_py

# fast build rule for target.
rosgraph_msgs_generate_messages_py/fast:
	$(MAKE) -f CMakeFiles/rosgraph_msgs_generate_messages_py.dir/build.make CMakeFiles/rosgraph_msgs_generate_messages_py.dir/build
.PHONY : rosgraph_msgs_generate_messages_py/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named simplePub

# Build rule for target.
simplePub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplePub
.PHONY : simplePub

# fast build rule for target.
simplePub/fast:
	$(MAKE) -f CMakeFiles/simplePub.dir/build.make CMakeFiles/simplePub.dir/build
.PHONY : simplePub/fast

#=============================================================================
# Target rules for targets named simpleSub

# Build rule for target.
simpleSub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleSub
.PHONY : simpleSub

# fast build rule for target.
simpleSub/fast:
	$(MAKE) -f CMakeFiles/simpleSub.dir/build.make CMakeFiles/simpleSub.dir/build
.PHONY : simpleSub/fast

#=============================================================================
# Target rules for targets named std_msgs_generate_messages_cpp

# Build rule for target.
std_msgs_generate_messages_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 std_msgs_generate_messages_cpp
.PHONY : std_msgs_generate_messages_cpp

# fast build rule for target.
std_msgs_generate_messages_cpp/fast:
	$(MAKE) -f CMakeFiles/std_msgs_generate_messages_cpp.dir/build.make CMakeFiles/std_msgs_generate_messages_cpp.dir/build
.PHONY : std_msgs_generate_messages_cpp/fast

#=============================================================================
# Target rules for targets named std_msgs_generate_messages_lisp

# Build rule for target.
std_msgs_generate_messages_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 std_msgs_generate_messages_lisp
.PHONY : std_msgs_generate_messages_lisp

# fast build rule for target.
std_msgs_generate_messages_lisp/fast:
	$(MAKE) -f CMakeFiles/std_msgs_generate_messages_lisp.dir/build.make CMakeFiles/std_msgs_generate_messages_lisp.dir/build
.PHONY : std_msgs_generate_messages_lisp/fast

#=============================================================================
# Target rules for targets named std_msgs_generate_messages_py

# Build rule for target.
std_msgs_generate_messages_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 std_msgs_generate_messages_py
.PHONY : std_msgs_generate_messages_py

# fast build rule for target.
std_msgs_generate_messages_py/fast:
	$(MAKE) -f CMakeFiles/std_msgs_generate_messages_py.dir/build.make CMakeFiles/std_msgs_generate_messages_py.dir/build
.PHONY : std_msgs_generate_messages_py/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named voice_node_gencpp

# Build rule for target.
voice_node_gencpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_gencpp
.PHONY : voice_node_gencpp

# fast build rule for target.
voice_node_gencpp/fast:
	$(MAKE) -f CMakeFiles/voice_node_gencpp.dir/build.make CMakeFiles/voice_node_gencpp.dir/build
.PHONY : voice_node_gencpp/fast

#=============================================================================
# Target rules for targets named voice_node_generate_messages

# Build rule for target.
voice_node_generate_messages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_generate_messages
.PHONY : voice_node_generate_messages

# fast build rule for target.
voice_node_generate_messages/fast:
	$(MAKE) -f CMakeFiles/voice_node_generate_messages.dir/build.make CMakeFiles/voice_node_generate_messages.dir/build
.PHONY : voice_node_generate_messages/fast

#=============================================================================
# Target rules for targets named voice_node_generate_messages_cpp

# Build rule for target.
voice_node_generate_messages_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_generate_messages_cpp
.PHONY : voice_node_generate_messages_cpp

# fast build rule for target.
voice_node_generate_messages_cpp/fast:
	$(MAKE) -f CMakeFiles/voice_node_generate_messages_cpp.dir/build.make CMakeFiles/voice_node_generate_messages_cpp.dir/build
.PHONY : voice_node_generate_messages_cpp/fast

#=============================================================================
# Target rules for targets named voice_node_generate_messages_lisp

# Build rule for target.
voice_node_generate_messages_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_generate_messages_lisp
.PHONY : voice_node_generate_messages_lisp

# fast build rule for target.
voice_node_generate_messages_lisp/fast:
	$(MAKE) -f CMakeFiles/voice_node_generate_messages_lisp.dir/build.make CMakeFiles/voice_node_generate_messages_lisp.dir/build
.PHONY : voice_node_generate_messages_lisp/fast

#=============================================================================
# Target rules for targets named voice_node_generate_messages_py

# Build rule for target.
voice_node_generate_messages_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_generate_messages_py
.PHONY : voice_node_generate_messages_py

# fast build rule for target.
voice_node_generate_messages_py/fast:
	$(MAKE) -f CMakeFiles/voice_node_generate_messages_py.dir/build.make CMakeFiles/voice_node_generate_messages_py.dir/build
.PHONY : voice_node_generate_messages_py/fast

#=============================================================================
# Target rules for targets named voice_node_genlisp

# Build rule for target.
voice_node_genlisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_genlisp
.PHONY : voice_node_genlisp

# fast build rule for target.
voice_node_genlisp/fast:
	$(MAKE) -f CMakeFiles/voice_node_genlisp.dir/build.make CMakeFiles/voice_node_genlisp.dir/build
.PHONY : voice_node_genlisp/fast

#=============================================================================
# Target rules for targets named voice_node_genpy

# Build rule for target.
voice_node_genpy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voice_node_genpy
.PHONY : voice_node_genpy

# fast build rule for target.
voice_node_genpy/fast:
	$(MAKE) -f CMakeFiles/voice_node_genpy.dir/build.make CMakeFiles/voice_node_genpy.dir/build
.PHONY : voice_node_genpy/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest.dir/build.make gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f gtest/CMakeFiles/gtest_main.dir/build.make gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/simplePub.o: src/simplePub.cpp.o
.PHONY : src/simplePub.o

# target to build an object file
src/simplePub.cpp.o:
	$(MAKE) -f CMakeFiles/simplePub.dir/build.make CMakeFiles/simplePub.dir/src/simplePub.cpp.o
.PHONY : src/simplePub.cpp.o

src/simplePub.i: src/simplePub.cpp.i
.PHONY : src/simplePub.i

# target to preprocess a source file
src/simplePub.cpp.i:
	$(MAKE) -f CMakeFiles/simplePub.dir/build.make CMakeFiles/simplePub.dir/src/simplePub.cpp.i
.PHONY : src/simplePub.cpp.i

src/simplePub.s: src/simplePub.cpp.s
.PHONY : src/simplePub.s

# target to generate assembly for a file
src/simplePub.cpp.s:
	$(MAKE) -f CMakeFiles/simplePub.dir/build.make CMakeFiles/simplePub.dir/src/simplePub.cpp.s
.PHONY : src/simplePub.cpp.s

src/simpleSub.o: src/simpleSub.cpp.o
.PHONY : src/simpleSub.o

# target to build an object file
src/simpleSub.cpp.o:
	$(MAKE) -f CMakeFiles/simpleSub.dir/build.make CMakeFiles/simpleSub.dir/src/simpleSub.cpp.o
.PHONY : src/simpleSub.cpp.o

src/simpleSub.i: src/simpleSub.cpp.i
.PHONY : src/simpleSub.i

# target to preprocess a source file
src/simpleSub.cpp.i:
	$(MAKE) -f CMakeFiles/simpleSub.dir/build.make CMakeFiles/simpleSub.dir/src/simpleSub.cpp.i
.PHONY : src/simpleSub.cpp.i

src/simpleSub.s: src/simpleSub.cpp.s
.PHONY : src/simpleSub.s

# target to generate assembly for a file
src/simpleSub.cpp.s:
	$(MAKE) -f CMakeFiles/simpleSub.dir/build.make CMakeFiles/simpleSub.dir/src/simpleSub.cpp.s
.PHONY : src/simpleSub.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... _voice_node_generate_messages_check_deps_voice_node"
	@echo "... clean_test_results"
	@echo "... download_extra_data"
	@echo "... doxygen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... roscpp_generate_messages_cpp"
	@echo "... roscpp_generate_messages_lisp"
	@echo "... roscpp_generate_messages_py"
	@echo "... rosgraph_msgs_generate_messages_cpp"
	@echo "... rosgraph_msgs_generate_messages_lisp"
	@echo "... rosgraph_msgs_generate_messages_py"
	@echo "... run_tests"
	@echo "... simplePub"
	@echo "... simpleSub"
	@echo "... std_msgs_generate_messages_cpp"
	@echo "... std_msgs_generate_messages_lisp"
	@echo "... std_msgs_generate_messages_py"
	@echo "... test"
	@echo "... tests"
	@echo "... voice_node_gencpp"
	@echo "... voice_node_generate_messages"
	@echo "... voice_node_generate_messages_cpp"
	@echo "... voice_node_generate_messages_lisp"
	@echo "... voice_node_generate_messages_py"
	@echo "... voice_node_genlisp"
	@echo "... voice_node_genpy"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/simplePub.o"
	@echo "... src/simplePub.i"
	@echo "... src/simplePub.s"
	@echo "... src/simpleSub.o"
	@echo "... src/simpleSub.i"
	@echo "... src/simpleSub.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

