set(_CATKIN_CURRENT_PACKAGE "voice_node")
set(voice_node_VERSION "0.0.0")
set(voice_node_MAINTAINER "Simone Magri <smagri@exemail.com.au>")
set(voice_node_PACKAGE_FORMAT "1")
set(voice_node_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(voice_node_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(voice_node_BUILDTOOL_DEPENDS "catkin")
set(voice_node_BUILDTOOL_EXPORT_DEPENDS )
set(voice_node_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(voice_node_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(voice_node_TEST_DEPENDS )
set(voice_node_DOC_DEPENDS )
set(voice_node_DEPRECATED "")